version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 202642037030.dkr.ecr.us-west-1.amazonaws.com
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t calendly_cd .
      - docker tag calendly:latest 202642037030.dkr.ecr.us-west-1.amazonaws.com/calendly_cd:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 202642037030.dkr.ecr.us-west-1.amazonaws.com/calendly_cd:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files: []
